version: '2'

services:
  app:
    build:
      context: .
    image: 'ecommerce:latest'
    container_name: app
    depends_on:
      - db
    environment:
      - ACTIVE_PROFILE=alpha
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wall_street
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=e_commerce
    ports:
      - "8081:8081"

  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wall_street
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
