server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wall_street
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
logging:
  level:
    root: WARN
    com.wallstreet.ecommerce: DEBUG